image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - chmod +x gradlew
  - java -jar ./artifacts/aqa-shop.jar -P:profile=test &

build_script:
  - ./gradlew test -Dselenide.headless=true --info
